// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3c_iX2wOs-FsOp4W5TqNbnc_grHJ86kk',
    appId: '1:931937718819:web:5b1df983fb8ff04d991796',
    messagingSenderId: '931937718819',
    projectId: 'sistemkaskelas',
    authDomain: 'sistemkaskelas.firebaseapp.com',
    storageBucket: 'sistemkaskelas.firebasestorage.app',
    measurementId: 'G-DDX7YBE94E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyTxX_BM4wdtAkMewi1q_f157_g5eEsSI',
    appId: '1:931937718819:android:1a4f530da45da848991796',
    messagingSenderId: '931937718819',
    projectId: 'sistemkaskelas',
    storageBucket: 'sistemkaskelas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDInjsxDLeQgWpLYm3nX4fo_mLAtbytZ-I',
    appId: '1:931937718819:ios:9c6256743eaa2e84991796',
    messagingSenderId: '931937718819',
    projectId: 'sistemkaskelas',
    storageBucket: 'sistemkaskelas.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDInjsxDLeQgWpLYm3nX4fo_mLAtbytZ-I',
    appId: '1:931937718819:ios:9c6256743eaa2e84991796',
    messagingSenderId: '931937718819',
    projectId: 'sistemkaskelas',
    storageBucket: 'sistemkaskelas.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3c_iX2wOs-FsOp4W5TqNbnc_grHJ86kk',
    appId: '1:931937718819:web:1c58cfb398558aa3991796',
    messagingSenderId: '931937718819',
    projectId: 'sistemkaskelas',
    authDomain: 'sistemkaskelas.firebaseapp.com',
    storageBucket: 'sistemkaskelas.firebasestorage.app',
    measurementId: 'G-L0G2S4W5WC',
  );
}
